#!/bin/bash

#if it doesnt work to schedule this with anacron, I could add a check if the
# logfile date is the same as today, and run it every hour

export DISPLAY=:0

idlefile=/home/lsund/Data/log/idle-active/idletime.log  
activefile=/home/lsund/Data/log/idle-active/activetime.log  
logfile=/home/lsund/Data/log/idle-active/day.log

min="5" 
idletime=$(xprintidle)
if [[ "$1" == "-ri" ]]; then
    echo "0" > $idlefile
elif [[ "$1" == "-ra" ]]; then
    echo "0" > $activefile
elif [[ "$1" == "-pi" ]]; then
    echo "$(cat $idlefile)"
elif [[ "$1" == "-pa" ]]; then
    echo "$(cat $activefile)"
elif [[ "$1" == "-pl" ]]; then
    echo "$(cat $logfile)"
elif [[ "$1" == "-sr" ]]; then # save and reset
    echo "$(date) idle: $(cat $idlefile)" >> $logfile
    echo "$(date) active: $(cat $activefile)" >> $logfile
    echo "0" > $idlefile
    echo "0" > $activefile
else
    if [[ "$idletime" -ge "250000" ]]; then
        curr_idle=$(cat $idlefile)
        new_idle=$(expr $curr_idle + $min)
        echo $new_idle > $idlefile
    else
        curr_active=$(cat $activefile)
        new_active=$(expr $curr_active + $min)
        echo $new_active > $activefile
    fi
fi


