#!/bin/bash

# Get how many available updates via pacman, store them in $file

file=/home/lsund/Data/log/pacman/pacsynccount.txt
wget -q --spider http://duckduckgo.com 

if [[ $? -eq 0 ]];
    then
        sudo pacman -Sy
        count="$(pacman -Qu | cut -d ' ' -f 1 | wc -l)"
        echo "$count" > $file
    else 
        echo "☒" > $file
fi
