#!/bin/bash

# For controlling the sound
statfile=/home/lsund/Data/log/sound/soundstat.txt
percfile=/home/lsund/Data/log/sound/soundperc.txt

stat=$(head -6 <(amixer) | grep % | cut -d " " -f 8 | cut -c2-3)

if [[ "$1" == "raise" ]]; then
    /usr/bin/amixer set Master 5%+
elif [[ "$1" == "lower" ]]; then
    /usr/bin/amixer set Master 5%-
else
    if [[ "$stat" == "of" ]]; then
        /usr/bin/amixer set Master on
        echo "on" > $statfile
    elif [[ "$stat" == "on" ]]; then
        /usr/bin/amixer set Master off
        echo "off" > $statfile
    fi
fi

perc=$(head -6 <(amixer) | grep % | cut -d " " -f 7 | cut -c2-4)

if [[ "$perc" == "100" ]]; then
    echo $perc"%" > $percfile
elif [[ "${perc:2:2}" == "]" ]]; then
    echo ${perc:0:2} > $percfile
else
    echo $perc > $percfile
fi

