#!/bin/env bash

# Automatically mount a device

if [[ $# != 1 ]]; then
    echo "Usage: automount usb|mybook"
    exit 1
fi

if [[ ! -d "/mnt/$1" ]]; then
    read -p "Create directory /mnt/$1? [Y/n] " ans
    if [[ $ans != "n" ]]; then
        sudo mkdir "/mnt/$1"
    else
        echo "Cannot mount. Exiting."
        exit 1
    fi
fi


lsblk
read -p "device name? please enter >> sdx(x) << " device

if [[ "$1" == "mybook" ]]; then
    path="/mnt/mybook"
elif [[ "$1" == "usb" ]]; then
    path="/mnt/usb"
else
    echo "unknown media" && exit
fi

sudo mount /dev/$device $path

if [[ "$?" == 0 ]]; then
    echo "$1 mounted on $path"
    cd $path
else
    echo "Something went wrong..." && exit
fi
