#!/bin/zsh

# Change to a directory in a pre-cached directory list, by entering a number or
# a substring

declare -a dirlist=(
    "/home/lsund/Documents/school/current/thesis/suffix-trees"
    "/home/lsund/Documents/school/current/thesis/wotd"
    "/home/lsund/Documents/school/current/thesis/mccreight"
    "/home/lsund/Documents/school/current/thesis/suffix-trees-haskell"
    "/home/lsund/Documents/scripts"
    "/home/lsund/Documents/dotfiles"
    "/home/lsund/Documents/tech/repos/calendar"
    "/home/lsund/Documents/tech/repos/jonnyh"
    "/home/lsund/Documents/tech/repos/myblog"
    "/home/lsund/Documents/tech/repos/projecteuler"
    "/home/lsund/Documents/tech/repos/haskellbook"
    "/home/lsund/Documents/work/application"
    )

declare -A dirmap

i=0
for d in $dirlist
do
    i=$(( i + 1 ))
    dirmap[$i]=$d
    [[ "$#" == 0 ]] && echo " $i \t $(basename $dirmap[$i])"
done

if [[ "$#" == 0 ]]; then
    vared -p "Choose (empty cancels) " -c choice
elif [[ "$#" == 1 ]]; then
    choice="$1"
fi

re='^[0-9]+$'
if ! [[ $choice =~ $re ]] ; then

    for d in $dirlist; do
        if [[ $d == *$choice* ]]; then
            target_109283749187023=$d
        fi
    done

else

    if [[ $choice && $(( $choice > 0 )) == 1 &&  $(( $choice <= i )) == 1 ]]; then
        target_109283749187023=${dirmap[$choice]}
    else
        echo "Number not in range"
    fi

fi

choice=""
dirmap=""
dirlist=""
i=""
[[ ! -d $target_109283749187023 ]] && echo "Malconfigured path" && exit 1
cd $target_109283749187023
