#!/bin/zsh

# if $1 is a file, count the lines in that file
# if $1 is a directory, count the number of items in the toplevel of that
# directory

if [[ -f $1 ]]; then
    cat $1 | wc -l
elif [[ -d $1 ]]; then
    ls $1 | wc -l
else
    echo $1: No suche file or directory
fi

