#!/bin/zsh

set -e

try-connect

files=$(git status | grep modified | xargs | cut -d' ' -f2,4,6,8)

basefiles=""
for file in $(echo $files | xargs); do
    basefiles+="$(basename $file), "
done

basefiles=${basefiles:0:-2}
msg="Modify $basefiles"

git add -A
git commit -m $msg
git status
git push
