#!/bin/bash

# Install script. Replaces sudo pacman -S <target>

distro="unknown"

which apt-get &> /dev/null
if [[ $? == "0" ]]; then
    distro="ubuntu"
fi

which pacman &> /dev/null
if [[ $? == "0" ]]; then
    distro="arch"
fi

if [[ $distro == "unknown" ]]; then
    echo "Unknown distro" && exit
fi

if [[ $distro == "arch" ]]; then
    pkgs="";
    normalinstall="true"
    for var in "$@"
        do
            if [[ "${var##*.}" == "xz" ]]; then
                sudo pacman -U $var
                normalinstall="false"
                break;
            fi
            pkgs+=$var
            pkgs+=" "
    done
    if [[ "$normalinstall" == "true" ]]; then
        for pkg in $pkgs
        do
            if [[ $(pacman -Ssq ^$pkg$) ]]; then
                sudo pacman -S $pkg
            else
                aurman -S $pkgs
            fi
        done
    fi
elif [[ $distro == "ubuntu" ]]; then
    pkgs="";
    for var in "$@"; do
        pkgs+=$var
        pkgs+=" "
    done
    for pkg in $pkgs
    do
        if [[ $(apt-cache search ^$pkg$) ]]; then
            sudo apt-get install $pkg
        else
            echo "Package does not appear in the apt repositories"
            echo "Try adding the correct ppa"
            exit
        fi
    done
fi
