#!/bin/bash

url=$1
filter=$2

[[ "$#" != 2 ]] && echo "Usage: get-urls-from-page URL FILTER" && exit 1

links=$(wget -O - $url | \
      grep -o '<a href=['"'"'"][^"'"'"']*['"'"'"]' | \
      sed -e 's/^<a href=["'"'"']//' -e 's/["'"'"']$//')

filtered=$(echo "$links" | grep $filter)

echo "$filtered" | while read line
do
    echo Found link: $line
done

read -p "Download? [y/n] " yn
case $yn in
    [Yy]* )
        echo $filtered | while read line
        do
            wget $line
        done
        ;;
    [Nn]* )
        echo "O-kay"
        ;;
    * ) echo "yes or no mate"
esac

