#!/bin/bash

# Courtesy to https://github.com/clarkema

if [ "$#" -gt 0 ]; then
   git checkout "$@"
else
    tags=$(git tag)
    branches=$(git branch --all)

    branch=$( (echo "HEAD~1" ; echo "$branches" ; echo "$tags") | "fzf" ) &&
    git checkout "$(echo "$branch" | sed "s/.* //" | sed "s#remotes/[^/]*/##")"
fi
