#!/bin/zsh

branch_name=$(git branch | grep \* | cut -d ' ' -f2)

project_name=$(echo $branch_name | cut -d '-' -f1)
issue_number=$(echo $branch_name | cut -d '-' -f2)

commit_tag=$project_name-$issue_number:

if [[ $1 == "ci" ]]; then
    vared -p "Commit Message: " -c msg
    git commit -m "$commit_tag $msg"
fi

git push -u origin $branch_name
