#!/bin/zsh

branch_name=$(git branch | grep \* | cut -d ' ' -f2)

project_name=$(echo $branch_name | cut -d '-' -f1)
issue_number=$(echo $branch_name | cut -d '-' -f2)

changes_status=$(git status | tail -1 | cut -d' ' -f1-5)

if [[ $changes_status == "no changes added to commit" || $changes_status == "nothing added to commit but" ]]; then
    git status
    vared -p  "Add all? [Y/n] " -c choice
    if [[ "$choice" == "n" ]]; then
        echo "Exiting..."
        exit 0;
    else
        git add --all
    fi
fi


if [[ $project_name == "HER" || $project_name == "DI" ]]; then
    commit_tag="$project_name-$issue_number: "
fi

if [[ $1 == "--nocommit" || $1 == "-n" ]]; then
    git push -u origin $branch_name
else
    vared -p "Commit Message: " -c msg
    git commit -m "$commit_tag$msg"
    git push -u origin $branch_name
fi
