#!/bin/zsh

dir=/home/lsund/Data/log/store
file=disk.txt

mkdir -p $dir
host=$(cat "/etc/hostname")

if [[ $host == "pedro" ]]; then
    device=sda2
elif [[ $host == "keysersoze" ]]; then
    device=nvme0n1p4
else
    echo "N/A" > $dir/$file && exit 1
fi

perc=$(df -h | grep $device | tr -s ' ' | cut -d' ' -f5)
echo $perc > $dir/$file
