#!/bin/zsh

SECONDS=0

control_c() {
    duration=$SECONDS
    echo $duration > .mplayer-elapsed
    exit
}

trap control_c SIGINT

while true ; do
    mplayer $1 | while read line ; do
        echo $line
    done
done

