#!/bin/zsh

SECONDS=0

control_c() {
    duration=$SECONDS
    touch .mplayer-elapsed
    echo $duration > .mplayer-elapsed
    if [[ $? != "0" ]]; then
        echo $duration > ~/.mplayer-elapsed
    fi
    exit
}

trap control_c SIGINT

# while true ; do
    mplayer $1 | while read line ; do
        echo $line
    done
# done

