#!/bin/zsh

trap control_c SIGINT

control_c () {
    unset word
    unset char
    unset file
    unset filemap
    found="true"
}

declare -A filemap

readChar() {
  stty -icanon -echo
  eval "$1=\$(dd bs=1 count=1 2>/dev/null)"
  stty icanon echo
}

function firstUnique () {
    file=$1
    i=$2
    for compare in $(ls -1)
    do
        if [[ $compare != $file && ${compare:0:$i} == ${file:0:$i} ]];
        then
            firstUnique $file $((i + 1))
            exit
        fi
    done
    echo ${file:0:$i}
}

for file in $(ls -1)
do
    res=$(firstUnique $file 0)
    key=$(echo $res | tr '[:upper:]' '[:lower:]')
    filemap[$key]=$key:$file
done

for a in $filemap
do
    echo $a
done

found="false"

while [[ $found == "false" ]]
do

    readChar char

    word=$word$char

    echo $word

    for entry in $filemap
    do
        key=$(echo $entry | cut -d':' -f1)
        value=$(echo $entry | cut -d':' -f2)

        if [[ $word == $key ]]; then
            echo $entry
            unset word
            cd $value
            found="true"
        fi
    done
done

unset word
unset char
unset file
unset filemap
