#!/bin/zsh

# Script to make rm more safe. Makes use of the `trash` script at any time your
# current directory is not a subdirectory of ~/.Trash.

path=$(pwd)

if [[ $path == $HOME/.trash* ]]; then
    /usr/bin/rm -rf "$@"
else
    /home/lsund/Documents/scripts/manual/trash "$@"
fi
