#!/bin/bash

# Script to make rm more safe. Makes use of the `trash` script at any time your
# current directory is not a subdirectory of ~/.Trash.

path=$(pwd)

if [[ $path == $HOME/.trash* ]]; then
    /usr/bin/rm -f "$@"
else
    /home/lsund/Documents/scripts/trash "$@"
fi
