#!/bin/zsh

less=false
for file in $@; do
    size=$(du -h $file | xargs | cut -d' ' -f1)
    value="${size:0:${#size}-1}"
    suffix="${size: -1}"
    if [[ $less == false && $suffix == "M" && $value -gt 50 ]]; then
        vared -p "File $file is larger than 50M. Open with less? [Y/n] " -c choice
        if [[ $choice != "n" ]]; then
            less=true
        fi
    fi
done

if [[ $less == true ]]; then
    less $@
else
    nvim $@
fi
