#!/bin/zsh

# ############################################################################
# Config

dir=/home/lsund/Data/log/sound
statfile=$dir/soundstat.txt
percfile=$dir/soundperc.txt

mkdir -p $dir
touch $statfile $percfile

function SetMuted() {
    muted=$(pactl list sinks | grep Mute | cut -d: -f2 | tail -n 1 | xargs)
    if [[ $muted == "no" ]]; then
        on_off="on"
    else
        on_off="off"
    fi
    echo $on_off > $statfile
}

function SetSink() {
    # Attempt to check if the sound stream is to a connected
    # Bluetooth device or not.
    is_bt=$(pactl list sinks | grep bluez)
    if [[ $is_bt == "" ]]; then
        sink_name=alsa_output.pci-0000_00_1f.3.analog-stereo
    else
        sink_name=bluez_sink.FC_58_FA_41_40_AD.a2dp_sink
    fi
}

SetSink

function SetPerc() {
    echo $(pactl list sinks | grep -A 8 $sink_name | grep Volume | xargs | cut -d' ' -f5) > $percfile
}

if [[ "$1" == "raise" ]]; then
     pactl -- set-sink-volume $sink_name +5%
     SetPerc
elif [[ "$1" == "lower" ]]; then
     pactl -- set-sink-volume $sink_name -5%
     SetPerc
 elif [[ "$1" == "toggle" ]]; then
        pactl -- set-sink-mute $sink_name toggle
        SetMuted
else
    exit 1
fi


