#!/bin/zsh

# ############################################################################
# Config

dir=/home/lsund/Data/log/sound
statfile=$dir/soundstat.txt
percfile=$dir/soundperc.txt

mkdir -p $dir
touch $statfile $percfile

hostname=$(< /etc/hostname)

function SetMuted() {
    if [[ $hostname == "pedro" ]]; then
        muted=$(pactl list sinks | grep Mute | cut -d: -f2 | head -n 1 | xargs)
    else
        muted=$(pactl list sinks | grep Mute | cut -d: -f2 | tail -n 1 | xargs)
    fi
    if [[ $muted == "no" ]]; then
        on_off="on"
    else
        on_off="off"
    fi
    echo $on_off > $statfile
}

# Sets the sink depending on the host
function SetSink() {
    is_bt=$(pactl list sinks | grep bluez)
    if [[ $hostname == "pedro" ]]; then
        sink_name=alsa_output.pci-0000_01_00.1.hdmi-stereo
    else
        sink_name=alsa_output.pci-0000_00_1f.3.analog-stereo
    fi
    # sink_name=bluez_sink.FC_58_FA_41_40_AD.a2dp_sink
}

SetSink

function SetPerc() {
    echo $(pactl list sinks | grep -A 8 $sink_name | grep Volume | xargs | cut -d' ' -f5) > $percfile
}

if [[ "$1" == "raise" ]]; then
     pactl -- set-sink-volume $sink_name +5%
     SetPerc
elif [[ "$1" == "lower" ]]; then
     pactl -- set-sink-volume $sink_name -5%
     SetPerc
 elif [[ "$1" == "toggle" ]]; then
        pactl -- set-sink-mute $sink_name toggle
        SetMuted
else
    exit 1
fi


