#!/bin/bash

function usage() {
    echo "Usage: ./remove-last-n-characters STRING N"
    echo Removes the last n characters from a string
    exit 0
}

if [[ $1 == "help" ]]; then
    usage
fi

if [[ $# == 2 ]]; then
    string=$1
    index=$2
else
    usage
fi

len=${#string}

prefix_len=$(($len - $index))

echo ${string:0:$prefix_len}
