#!/bin/zsh

# Script for facilitating the pacman -Syu and related commands

scriptdir=/home/lsund/Documents/scripts/

if [[ -e "/etc/pacman.d/mirrorlist" && -e "/etc/pacman.d/mirrorlist.pacnew" ]];
then
    vared -p "A new mirrorlist file exists. Use that instead? [Y/n] " -c choice
    if [[ "$choice" != "n" ]]; then
        sudo /etc/pacman.d/mirrorlist-merger-exe
    fi
fi

aurman -Suy

$scriptdir/pacsync
