#!/bin/zsh

ext=$(extension $1)

if [[ $ext == "gz" && $(extension $1 2) == "tar" || $ext == "tgz" ]]; then
    tar -xvzf $1
elif [[ $ext == "gz" ]]; then
    gunzip $1
elif [[ $ext == "zip" ]]; then
    unzip $1
elif [[ $ext == "7z" ]]; then
    un7z $1
elif [[ $ext == "jar" ]]; then
    jar xf $1
elif [[ $ext == "tar" ]]; then
    tar -xvf $1
elif [[ $ext == "rpm" ]]; then
    rpmextract.sh $1
else
    echo "Unknown extension: $ext"
fi

