#!/bin/zsh

# TODO Scan for networks and select something
sudo wifi-menu
if [[ "$?" == "0" ]]; then
    try-connect
else
    echo "Something didnt check out. Exiting..."
    vared -p "Set link down [Y/n]? " -c choice

    [[ "$choice" == "n" ]] && exit 0

    sudo ip link set wlp58s0 down
    sudo wifi-menu

fi



