#!/bin/zsh

# Automatically mount a device

lsblk
read -p "device name? please enter >> sdxx << " device

if [[ "$1" == "mybook" ]]; then
    path="/mnt/mybook"
elif [[ "$1" == "usb" ]]; then
    path="/mnt/usb"
else
    echo "unknown media" && exit
fi

sudo mount /dev/$device $path

if [[ "$?" == 0 ]]; then
    echo "$1 mounted on $path"
else
    echo "Something went wrong..." && exit
fi
