#!/bin/bash

# Automatically mount some device

lsblk
read -p "device name? please enter >> sdxx << " device

if [[ "$1" == "mybook" ]]; then
    sudo mount /dev/$device /mnt/mybook
elif [[ "$1" == "usb" ]]; then
    sudo mount /dev/$device /mnt/usb
else
    echo "unknown media"
fi

