#!/bin/bash

# Small timer script

prefix=${1:0:${#1}-1}
suffix=${1:${#1}-1:${#1}}
if [[ $suffix == "s" ]]; then
    date1=$((`date +%s` + $prefix)); 
    while [ "$date1" -ge `date +%s` ]; do 
        echo -ne "$(date -u --date @$(($date1 - `date +%s`)) +%H:%M:%S)\r";
        sleep 0.1
    done
    mplayer ~/Audio/system-sound-files/bell.mp3 > /dev/null 2>&1
elif [[ $suffix == "m" ]]; then
    date1=$((`date +%s` + $((60*$prefix)))); 
    while [ "$date1" -ge `date +%s` ]; do 
        echo -ne "$(date -u --date @$(($date1 - `date +%s`)) +%H:%M:%S)\r";
        sleep 0.1
    done
    mplayer ~/Audio/system-sound-files/bell.mp3 > /dev/null 2>&1
elif [[ $suffix == "h" ]]; then
    date1=$((`date +%s` + $((60*60*$prefix)))); 
    while [ "$date1" -ge `date +%s` ]; do 
        echo -ne "$(date -u --date @$(($date1 - `date +%s`)) +%H:%M:%S)\r";
        sleep 0.1
    done
    mplayer ~/Audio/system-sound-files/bell.mp3 > /dev/null 2>&1
else
    echo "Invalid argument to countdown()"
fi

