#!/bin/bash

# Install script. Replaces sudo pacman -S <target>

all="";
normalinstall="true"
for var in "$@"
    do 
        if [[ "${var##*.}" == "xz" ]]; then
            sudo pacman -U $var
            normalinstall="false"
            break;
        fi
        all+=$var
        all+=" "
done
if [[ "$normalinstall" == "true" ]]; then
    #if [[ $(pacman -Ssq ^$all$) ]]; then
        #sudo pacman -S $all
    #else
        pacaur -S $all
    #fi
fi
