#!/bin/bash

# Install script. Replaces sudo pacman -S <target>

pkgs="";
normalinstall="true"
for var in "$@"
    do
        if [[ "${var##*.}" == "xz" ]]; then
            sudo pacman -U $var
            normalinstall="false"
            break;
        fi
        pkgs+=$var
        pkgs+=" "
done
if [[ "$normalinstall" == "true" ]]; then
    for pkg in $pkgs
    do
        if [[ $(pacman -Ssq ^$pkg$) ]]; then
            sudo pacman -S $pkg
        else
            pacaur -S $pkgs
        fi
    done
fi
