#!/bin/zsh

scriptdir=$HOME/Documents/scripts
dotfilesdir=$HOME/Documents/dotfiles
orgdir=$HOME/Documents/org

if [[ ! -d $orgdir ]]; then
    git -C $HOME/Documents clone git@github.com:/lsund/org
fi

if [[ "$#" == "0" ]]; then
    echo "Usage: gitsync push|pull [MESSAGE]" && exit
elif [[ "$#" == "1" ]]; then
    action=$1
    msg="Update: "$(date)
    if [[ $action == "push" ]]; then

	echo "##################################################################"
	echo "## Pushing $msg to $dotfilesdir"

        git -C $dotfilesdir a
        git -C $dotfilesdir ci -m "$msg"
        git -C $dotfilesdir "push"

	echo "##################################################################"
p	echo "## Pushing $msg to $scritpdir"

        git -C $scriptdir a
        git -C $scriptdir ci -m "$msg"
        git -C $scriptdir "push"

	echo "##################################################################"
	echo "## Pushing $msg to $orgdir"

        git -C $orgdir a
        git -C $orgdir ci -m "$msg"
        git -C $orgdir "push"

    elif [[ $action == "pull" ]]; then
	
	echo "##################################################################"
	echo "## Pulling from $dotfilesdir"
        git -C $dotfilesdir "pull"
	
	echo "##################################################################"
	echo "## Pulling from $scriptdir"
        git -C $scriptdir "pull"

	echo "##################################################################"
	echo "## Pulling from $orgdir"
        git -C $orgdir "pull"

    else
        echo "Unknown command: $action"
    fi
elif [[ "$#" == "2" ]]; then
    action=$1
    msg=$2
    if [[ $action == "push" ]]; then

        git -C $dotfilesdir a
        git -C $dotfilesdir ci -m "$msg"
        git -C $dotfilesdir "push"

        git -C $scriptdir a
        git -C $scriptdir ci -m "$msg"
        git -C $scriptdir "push"

        git -C $orgdir a
        git -C $orgdir ci -m "$msg"
        git -C $orgdir "push"

    elif [[ $action == "pull" ]]; then
        git -C $dotfilesdir "pull"
        git -C $scriptdir "pull"
        git -C $orgdir "pull"
    else
        echo "Unknown command: $action"
    fi
elif [[ "$#" == "3" ]]; then
    action=$1
    filter=$2
    dir=$3
    # TODO
    if [[ $dir == "org" ]]; then
        git -C $orgdir $action
    fi
fi
