#!/bin/bash

scriptdir=$HOME/Documents/scripts
dotfilesdir=$HOME/Documents/dotfiles
orgdir=$HOME/Documents/org

if [[ "$#" == "0" ]]; then
    echo "Usage: gitsync push|pull [MESSAGE]"
elif [[ "$#" == "1" ]]; then
    action=$1
    msg="Update: "$(date)
elif [[ "$#" == "1" ]]; then
    action=$1
    msg=$2
fi

git -C $dotfilesdir a
git -C $dotfilesdir ci -m "$msg"
git -C $dotfilesdir $action

git -C $scriptdir a
git -C $scriptdir ci -m "$msg"
git -C $scriptdir $action

git -C $orgdir a
git -C $orgdir ci -m "$msg"
git -C $orgdir $action


