#!/bin/zsh

vimrc=$HOME/.vimrc
vim=$HOME/.vim
VIM=$HOME/.vim
al=$HOME/.aliases
git=$HOME/.config/git/config
emacsd=$HOME/.emacs.d

# Make some directories
mkdir -p $vim/{after/plugin,colors,plugin}
mkdir -p $emacsd/config
mkdir -p $HOME/.config/git
mkdir -p $HOME/.git_template/hooks
mkdir -p $HOME/.xmonad/lib
mkdir -p $HOME/.xmonad/apps
mkdir -p $HOME/.xmonad/img
mkdir -p $HOME/.icons/xbm_icons/subtle

## Sources

# Vim
zsh_plugin=$DOTFILES/vim/after/plugin/zsh.vim
haskell_plugin=$DOTFILES/vim/after/plugin/haskell.vim
python_plugin=$DOTFILES/vim/after/plugin/python.vim
clojure_plugin=$DOTFILES/vim/after/plugin/clojure.vim

vim_rc=$DOTFILES/vimrc
vim_badwolf=$DOTFILES/vim/colors/badwolf.vim

vim_ack=$DOTFILES/vim/plugin/ack.vim
vim_airline=$DOTFILES/vim/plugin/airline.vim
vim_bufonly=$DOTFILES/vim/plugin/BufOnly.vim
vim_easymotion=$DOTFILES/vim/plugin/easymotion.vim
vim_fugitive=$DOTFILES/vim/plugin/fugitive.vim
vim_fzf=$DOTFILES/vim/plugin/fzf.vim
vim_himport=$DOTFILES/vim/plugin/HaskellImport.vim
vim_hlint_refactor=$DOTFILES/vim/plugin/hlint-refactor.vim
vim_intero=$DOTFILES/vim/plugin/intero.vim
vim_nerdtree=$DOTFILES/vim/plugin/nerdtree.vim
vim_plugin=$DOTFILES/vim/plugin/plugin.vim
vim_rainbow=$DOTFILES/vim/plugin/rainbow-parentheses.vim
vim_rename=$DOTFILES/vim/plugin/Rename.vim
vim_syntastic=$DOTFILES/vim/plugin/syntastic.vim
vim_tabular=$DOTFILES/vim/plugin/tabular.vim
vim_tagbar=$DOTFILES/vim/plugin/tagbar.vim
vim_tmuxnav=$DOTFILES/vim/plugin/tmuxnavigate.vim
vim_ultisnips=$DOTFILES/vim/plugin/ultisnips.vim
vim_easy=$DOTFILES/vim/plugin/vim-easy-align.vim
vim_incr=$DOTFILES/vim/plugin/visincrPlugin.vim
vim_ycm=$DOTFILES/vim/plugin/ycm.vim


# Emacs
emacs_file=$DOTFILES/emacs/emacs
emacs_init=$DOTFILES/emacs/init.el
emacs_config=$DOTFILES/emacs/config/my-config.el
emacs_keybindings=$DOTFILES/emacs/config/my-keybindings.el
emacs_clojure=$DOTFILES/emacs/config/my-clojure.el
emacs_elisp=$DOTFILES/emacs/config/my-elisp.el
emacs_powerline=$DOTFILES/emacs/config/my-powerline.el
emacs_haskell=$DOTFILES/emacs/config/my-haskell.el
emacs_org=$DOTFILES/emacs/config/my-org.el
emacs_lisp=$DOTFILES/emacs/config/my-lisp.el
emacs_python=$DOTFILES/emacs/config/my-python.el
emacs_tex=$DOTFILES/emacs/config/my-tex.el
emacs_md=$DOTFILES/emacs/config/my-markdown.el

# Git
git_config=$DOTFILES/git/config
git_hook_prepare_commit_msg=$DOTFILES/git/hooks/prepare-commit-msg

# SSH
ssh_config=$DOTFILES/ssh/config

# Misc
zsh_rc=$DOTFILES/zshrc
_aliases="$DOTFILES/aliases"
tmux=$DOTFILES/tmux.conf
xinitrc=$DOTFILES/xinitrc
xresources=$DOTFILES/Xresources

# XMonad
xmonadrc=$DOTFILES/xmonad/xmonad.hs
xm_boxes=$DOTFILES/xmonad/Boxes.hs
xm_config=$DOTFILES/xmonad/Config.hs
xm_keys=$DOTFILES/xmonad/KeyBindings.hs
xm_cpu=$DOTFILES/xmonad/haskell-cpu-usage.out
xm_img=$DOTFILES/xmonad/haskell.png

xm_icon1=$DOTFILES/icons/boxleft2-big.xbm
xm_icon2=$DOTFILES/icons/boxleft2.xbm
xm_icon3=$DOTFILES/icons/boxleft.xbm
xm_icon4=$DOTFILES/icons/boxright.xbm

## Destinations

# Vim
loc_zsh_plugin=$VIM/after/plugin/zsh.vim
loc_haskell_plugin=$VIM/after/plugin/haskell.vim
loc_python_plugin=$VIM/after/plugin/python.vim
loc_clojure_plugin=$VIM/after/plugin/clojure.vim

loc_vim_rc=$HOME/.vimrc
loc_vim_badwolf=$HOME/.vim/colors/badwolf.vim

loc_vim_ack=$HOME/.vim/plugin/ack.vim
loc_vim_airline=$HOME/.vim/plugin/airline.vim
loc_vim_bufonly=$HOME/.vim/plugin/BufOnly.vim
loc_vim_easymotion=$HOME/.vim/plugin/easymotion.vim
loc_vim_fugitive=$HOME/.vim/plugin/fugitive.vim
loc_vim_fzf=$HOME/.vim/plugin/fzf.vim
loc_vim_himport=$HOME/.vim/plugin/HaskellImport.vim
loc_vim_hlint_refactor=$HOME/.vim/plugin/hlint-refactor.vim
loc_vim_intero=$HOME/.vim/plugin/intero.vim
loc_vim_nerdtree=$HOME/.vim/plugin/nerdtree.vim
loc_vim_plugin=$HOME/.vim/plugin/plugin.vim
loc_vim_rainbow=$HOME/.vim/plugin/rainbow-parentheses.vim
loc_vim_rename=$HOME/.vim/plugin/Rename.vim
loc_vim_syntastic=$HOME/.vim/plugin/syntastic.vim
loc_vim_tabular=$HOME/.vim/plugin/tabular.vim
loc_vim_tagbar=$HOME/.vim/plugin/tagbar.vim
loc_vim_tmuxnav=$HOME/.vim/plugin/tmuxnavigate.vim
loc_vim_ultisnips=$HOME/.vim/plugin/ultisnips.vim
loc_vim_easy_align=$HOME/.vim/plugin/vim-easy-align.vim
loc_vim_incr=$HOME/.vim/plugin/visincrPlugin.vim
loc_vim_ycm=$HOME/.vim/plugin/ycm.vim

# Emacs

loc_emacs_file=$HOME/.emacs
loc_emacs_init=$emacsd/init.el
loc_emacs_config=$emacsd/config/my-config.el
loc_emacs_keybindings=$emacsd/config/my-keybindings.el
loc_emacs_clojure=$emacsd/config/my-clojure.el
loc_emacs_elisp=$emacsd/config/my-elisp.el
loc_emacs_powerline=$emacsd/config/my-powerline.el
loc_emacs_haskell=$emacsd/config/my-haskell.el
loc_emacs_org=$emacsd/config/my-org.el
loc_emacs_lisp=$emacsd/config/my-lisp.el
loc_emacs_python=$emacsd/config/my-python.el
loc_emacs_tex=$emacsd/config/my-tex.el
loc_emacs_md=$emacsd/config/my-markdown.el

# Git
loc_git_config=$HOME/.config/git/config
loc_git_hook_prepare_commit_msg=$HOME/.git_template/hooks/prepare-commit-msg

# SSH
loc_ssh_config=$HOME/.ssh/config

# Misc
loc_zsh_rc=$HOME/.zshrc
loc_aliases="$HOME/.aliases"
loc_tmux=$HOME/.tmux.conf
loc_xinitrc=$HOME/.xinitrc
loc_xresources=$HOME/.Xresources

# XMonad
loc_xmonadrc=$HOME/.xmonad/xmonad.hs
loc_xm_boxes=$HOME/.xmonad/lib/Boxes.hs
loc_xm_config=$HOME/.xmonad/lib/Config.hs
loc_xm_keys=$HOME/.xmonad/lib/KeyBindings.hs
loc_xm_cpu=$HOME/.xmonad/apps/haskell-cpu-usage.out
loc_xm_img=$HOME/.xmonad/img/haskell.png

loc_xm_icon1=$HOME/.icons/xbm_icons/subtle/boxleft2-big.xbm
loc_xm_icon2=$HOME/.icons/xbm_icons/subtle/boxleft2.xbm
loc_xm_icon3=$HOME/.icons/xbm_icons/subtle/boxleft.xbm
loc_xm_icon4=$HOME/.icons/xbm_icons/subtle/boxright.xbm

## Insertions

# Vim
[[ -f $loc_zsh_plugin ]]        || ln -s $zsh_plugin        $loc_zsh_plugin
[[ -f $loc_haskell_plugin ]]    || ln -s $haskell_plugin    $loc_haskell_plugin
[[ -f $loc_python_plugin ]]     || ln -s $python_plugin     $loc_python_plugin
[[ -f $loc_clojure_plugin ]]    || ln -s $clojure_plugin    $loc_clojure_plugin

[[ -f $loc_vim_rc ]]            || ln -s $vim_rc            $loc_vim_rc
[[ -f $loc_vim_badwolf ]]       || ln -s $vim_badwolf       $loc_vim_badwolf

[[ -f $loc_vim_tmuxnav ]]       || ln -s $vim_tmuxnav       $loc_vim_tmuxnav

[[ -f $loc_vim_ack ]]           || ln -s $vim_ack           $loc_vim_ack
[[ -f $loc_vim_airline ]]       || ln -s $vim_airline       $loc_vim_airline
[[ -f $loc_vim_bufonly ]]       || ln -s $vim_bufonly       $loc_vim_bufonly
[[ -f $loc_vim_easymotion ]]    || ln -s $vim_easymotion    $loc_vim_easymotion
[[ -f $loc_vim_fugitive   ]]    || ln -s $vim_fugitive      $loc_vim_fugitive
[[ -f $loc_vim_fzf ]]           || ln -s $vim_fzf           $loc_vim_fzf
[[ -f $loc_vim_himport ]]       || ln -s $vim_himport       $loc_vim_himport
[[ -f $loc_vim_hlint_refactor ]] || ln -s $vim_hlint_refactor $loc_vim_hlint_refactor
[[ -f $loc_vim_intero  ]]       || ln -s $vim_intero        $loc_vim_intero
[[ -f $loc_vim_nerdtree    ]]   || ln -s $vim_nerdtree      $loc_vim_nerdtree
[[ -f $loc_vim_plugin  ]]       || ln -s $vim_plugin        $loc_vim_plugin
[[ -f $loc_vim_rainbow ]]       || ln -s $vim_rainbow       $loc_vim_rainbow
[[ -f $loc_vim_rename  ]]       || ln -s $vim_rename        $loc_vim_rename
[[ -f $loc_vim_syntastic   ]]   || ln -s $vim_syntastic     $loc_vim_syntastic
[[ -f $loc_vim_tabular ]]       || ln -s $vim_tabular       $loc_vim_tabular
[[ -f $loc_vim_tagbar  ]]       || ln -s $vim_tagbar        $loc_vim_tagbar
[[ -f $loc_vim_tmuxnav ]]       || ln -s $vim_tmuxnav       $loc_vim_tmuxnav
[[ -f $loc_vim_ultisnips   ]]   || ln -s $vim_ultisnips     $loc_vim_ultisnips
[[ -f $loc_vim_easy  ]]   || ln -s $vim_easy          $loc_vim_easy
[[ -f $loc_vim_incr    ]]       || ln -s $vim_incr          $loc_vim_incr
[[ -f $loc_vim_ycm ]]           || ln -s $vim_ycm           $loc_vim_ycm

# Emacs
[[ -f $loc_emacs_file ]]        || ln -s $emacs_file        $loc_emacs_file
[[ -f $loc_emacs_init ]]        || ln -s $emacs_init        $loc_emacs_init
[[ -f $loc_emacs_config ]]      || ln -s $emacs_config      $loc_emacs_config
[[ -f $loc_emacs_keybindings ]] || ln -s $emacs_keybindings $loc_emacs_keybindings
[[ -f $loc_emacs_clojure ]]     || ln -s $emacs_clojure     $loc_emacs_clojure
[[ -f $loc_emacs_elisp ]]       || ln -s $emacs_elisp       $loc_emacs_elisp
[[ -f $loc_emacs_powerline ]]   || ln -s $emacs_powerline   $loc_emacs_powerline
[[ -f $loc_emacs_haskell ]]     || ln -s $emacs_haskell     $loc_emacs_haskell
[[ -f $loc_emacs_org ]]         || ln -s $emacs_org         $loc_emacs_org
[[ -f $loc_emacs_lisp ]]        || ln -s $emacs_lisp        $loc_emacs_lisp
[[ -f $loc_emacs_python ]]      || ln -s $emacs_python      $loc_emacs_python
[[ -f $loc_emacs_tex ]]         || ln -s $emacs_tex         $loc_emacs_tex
[[ -f $loc_emacs_md ]]          || ln -s $emacs_md          $loc_emacs_md

# Git
[[ -f $loc_git_config ]]        || ln -s $git_config        $loc_git_config
[[ -f $loc_git_hook_prepare_commit_msg ]] ||
    ln -s $git_hook_prepare_commit_msg  $loc_git_hook_prepare_commit_msg

# SSH
[[ -f $loc_ssh_config ]]        || ln -s $ssh_config        $loc_ssh_config

# Misc
[[ -f $loc_zsh_rc ]]            || ln -s $zsh_rc            $loc_zsh_rc
[[ -f $loc_aliases ]]           || ln -s $_aliases          $loc_aliases
[[ -f $loc_tmux ]]              || ln -s $tmux              $loc_tmux
[[ -f $loc_xinitrc ]]           || ln -s $xinitrc           $loc_xinitrc
[[ -f $loc_xresources ]]        || ln -s $xresources        $loc_xresources

# XMonad
[[ -f $loc_xmonadrc ]]          || ln -s $xmonadrc          $loc_xmonadrc
[[ -f $loc_xm_boxes ]]          || ln -s $xm_boxes          $loc_xm_boxes
[[ -f $loc_xm_config ]]         || ln -s $xm_config         $loc_xm_config
[[ -f $loc_xm_keys ]]           || ln -s $xm_keys           $loc_xm_keys
[[ -f $loc_xm_cpu ]]            || ln -s $xm_cpu            $loc_xm_cpu
[[ -f $loc_xm_img ]]            || ln -s $xm_img            $loc_xm_img

[[ -f $loc_xm_icon1 ]]          || ln -s $xm_icon1          $loc_xm_icon1
[[ -f $loc_xm_icon2 ]]          || ln -s $xm_icon2          $loc_xm_icon2
[[ -f $loc_xm_icon3 ]]          || ln -s $xm_icon3          $loc_xm_icon3
[[ -f $loc_xm_icon4 ]]          || ln -s $xm_icon4          $loc_xm_icon4

echo "Done"
echo "You probably need to source $loc_aliases"
