#!/bin/zsh


if [[ "$#" == 0 ]]; then
    host="www.duckduckgo.com"
else
    host="$1"
fi

while true
do
    ping -c 1 $host 1> /dev/null
    if [[ "$?" == "0" ]]; then
        echo "Connected..." && exit
    fi
    sleep 3
done
