#!/bin/zsh

# Script to make rm more safe. Makes use of the `trash` script at any time your
# current directory is not a subdirectory of ~/.Trash.

path=$(pwd)

if [[ $path == $HOME/.Trash* ]]; then
    /usr/bin/rm "$@"
else
    trash "$@"
fi
