#!/bin/zsh

: ${DOTFILES?"Need to set env variable: DOTFILES"}

vimrc=$HOME/.vimrc
vim=$HOME/.vim
vundle=$HOME/.vim/bundle/Vundle.vim
al=$HOME/.aliases
git=$HOME/.config/git/config

if [[ ! -e $vimrc ]]; then
    ln -s $DOTFILES/vimrc $vimrc
fi

if [[ ! -e $vim ]]; then
    ln -s $DOTFILES/vim $vim
fi

if [[ ! -e $git ]]; then
    mkdir -p $HOME/.config/git
    ln -s $DOTFILES/git/config $git
fi

if [[ ! -e $vundle ]]; then
    git clone https://github.com/VundleVim/Vundle.vim.git $vundle
fi

if [[ ! -e $al ]]; then
    ln -s $DOTFILES/aliases $al
fi

which trans
if [[ $? == "1" ]]; then
    wget git.io/trans
    chmod +x ./trans
    mv trans $HOME/bin
fi

sudo apt-get update && sudo apt-get upgrade
declare -a packages=("htop" "ruby" "ghc" "silversearcher-ag" "pwgen"
                     "build-essential" "cmake" "python-dev" "python3-dev"
                     "python3-venv" "g++" "redshift)

for package in "${packages[@]}"
do
    dpkg -s $package > /dev/null 2>&1
    if [[ $? == "1" ]]; then
        sudo apt-get install $package
    fi
done

# You Complete Me
ycm_core="$vim/bundle/YouCompleteMe/third_party/ycmd/ycm_core.so" 
if [[ ! -e $ycm_core ]]; then
    $vim/bundle/YouCompleteMe/install.py
fi

