#!/bin/zsh

# ############################################################################
# Config


dir="$HOME/Data/log/timelog/"

logpath="$dir$file"

quiet=false

class=false

# ############################################################################
# Usage


function usage() {
cat << EOF
USAGE:

   study-tracker [ -vlcrd ]

OPTIONS:
   -h            : Help
   -v            : Verbose
   -l            : List classes
   -t CLASS      : Start logging time for the giver CLASS
   -d CLASS      : Display the current time for the given CLASS
   -r            : Reset the timer for the given CLASS
   -c CLASS      : Specify CLASS
   -a TIME       : Add TIME seconds for the given CLASS specified by -c

This is a program for logging time spent on various things. The things are
called classes. If you want to start or continue working on something, specify
it with the -c option.

EOF
}

function init()
{
    echo "Start date: $(date +%y-%m-%d)" > $1
    echo "0" >> $1
}

# ############################################################################
#

while getopts "hqlc:t:r:d:a:" opt; do
    case "$opt" in
        h)
            usage && exit 0
            ;;
        q)
            quiet=true
            ;;
        l)
            ls $dir && exit 0
            ;;
        c)
            class="$OPTARG"
            logpath=$dir$class
            ;;
        t)
            class="$OPTARG"
            logpath=$dir$class
            [[ ! -e $logpath ]] && init $logpath
            ;;
        r)
            class="$OPTARG"
            logpath=$dir$class
            sed -i '2s/.*/0/' $logpath
            exit 0
            ;;
        d)
            class="$OPTARG"
            logpath=$dir$class
            cat $logpath
            exit 0
            ;;
        a)
            [[ "$class" == false ]] && echo "Must specify -c" && exit 1
            time="$OPTARG"
            logpath=$dir$class
            newtime=$(( $(cat $logpath | tail -1) + time ))
            sed -i "2s/.*/$newtime/" $logpath
            exit 0
            ;;
        *)
            usage && exit
            ;;
    esac
done 2>/dev/null

[[ "$class" == false ]] && usage && exit 1

i=$(tail -1 $logpath)
while true; do

    sed -i "2s/.*/$i/" $logpath
    /usr/bin/sleep 1
    i=$((i + 1))
    day="$(date -u --date @$i +%d)"
    day=$(($day - 1))
    hour="$(date -u --date @$i +%H:%M:%S)"
    date_string="0$day:$hour"

    if [[ $quiet == false && $((i%60)) == "0" ]]; then
        echo $date_string
    fi

done

