#!/bin/zsh

# 'Move to trash'. Simply move some items to ~/.Trash and keep track of copies

# Config
#
warning_kilo_bytes=5000
trashdir="$HOME/.Trash/"

#  Code

mkdir -p $trashdir

for var in "$@"
    do
        basevar=$(basename "$var")
        if [[ -e "$var" ]]; then
            max=0
            for existing in  $(ls $trashdir | grep $var-trashed)
            do
                num=$(echo $existing | cut -d'-' -f3)
                if [[  $num -gt max ]]; then
                    max=$num
                fi
            done
            mv $var $trashdir$basevar-trashed-$(( $max + 1 ))
        elif
            [[ -L "$var" ]]; then
            /usr/bin/rm $var
        else
            echo "trash: no such file or directory: $var"
        fi
done

echo
bytes=$(du -s $trashdir)
number=$(echo $bytes | cut -d'/' -f1 | xargs)

if [[ "$number" -gt "$warning_kilo_bytes"  ]]; then
    echo "Consider empty trash directory"
    echo "It currently stores $(echo $number | xargs) KB of unused bananas"
fi
