#!/bin/bash

# 'Move to trash'. Simply move some items to ~/.Trash

warning_gigs=5

trashdir="/home/lsund/.Trash/"
for var in "$@"
    do 
        basevar=$(basename "$var")
        if [[ -e "$var" ]]; then
            if [[ -e "$trashdir$basevar" ]]; then
                randstr="$(pwgen 13 1)"
                sudo mv "$var" "$trashdir$basevar-$randstr"
            else
                sudo mv "$var" "$trashdir"
            fi 
        else
            echo "trash: no such file or directory: $var"
        fi
done

bytesFull=$(du -hs $trashdir)
bytes=(${bytesFull// / })
len=${#bytes} 
number=${bytes:0:len-1}
suffix=${bytes:len-1:len}

if [[ "$number" > "$warning_gigs" && "$suffix" == "G" ]]; then
    echo "Consider empty trash directory"
    echo "It currently stors "$bytes "unused bananas"
fi
