#!/bin/zsh

# Config

trashdir="$HOME/.Trash/"
warning_kilo_bytes=5000

# Preconditions

if [[ -e "/usr/bin/rm" ]]; then
    real_remove=/usr/bin/rm
elif [[ -e "/bin/rm" ]]; then
    real_remove=/bin/rm
else
    echo "Don't know which rm to use" && exit
fi

mkdir -p $trashdir

# Code

if [[ "$1" == "-l" ]]; then
    case "$#" in
        "1")
            /usr/bin/ls $trashdir
            ;;
        "2")
            /usr/bin/ls $trashdir | grep --color=auto $2
            ;;
        *)
            exit
    esac
    exit
fi

for var in "$@"
    do
        basevar=$(basename "$var")
        if [[ -e "$var" ]]; then
            max=0
            for existing in  $(ls $trashdir | grep $var-trashed)
            do
                num=$(echo $existing | cut -d'-' -f3)
                if [[  $num -gt max ]]; then
                    max=$num
                fi
            done
            mv $var $trashdir$basevar-trashed-$(( $max + 1 ))
            echo "Moved to Trash"
        elif
            [[ -L "$var" ]]; then
            $real_remove $var
        else
            echo "trash: no such file or directory: $var"
        fi
done

echo

bytes=$(du -s $trashdir)
number=$(echo $bytes | cut -d'/' -f1 | xargs)

if [[ "$number" -gt warning_kilo_bytes ]]; then


    unit="KB"
    if [[ "$number" -gt "1000" ]]; then
        unit="MB"
        number=$(expr $number / 1000)
    fi
    if [[ "$number" -gt "1000" ]]; then
        unit="GB"
        number=$(expr $number / 1000)
    fi

    echo "Consider empty trash directory"
    echo "It currently more than $(echo $number | xargs) $unit"
fi
