#!/bin/zsh


if [[ "$#" == 0 ]]; then
    host="www.duckduckgo.com"
else
    host="$1"
fi

echo "Trying to connect..."
while true
do
    ping -c 1 $host > /dev/null 2>&1
    if [[ "$?" == "0" ]]; then
        echo "Connected..." && exit
    fi
    sleep 3
done
