#!/bin/zsh

if [[ $# -lt "2" ]]; then
    echo "Need 2 arguments: ww LINE FILE" && exit
fi

case $# in
    "2")
        # TODO What is this??
        # if [[ $1 == "-d" ]]; then
        #     sed -i '$ d' $2
        #     cat $2
        # else
            echo $1 >> $2
            cat $2
        # fi
        ;;
    * ) echo "Need 2 arguments: ww LINE FILE" && exit
esac

